# Generated by Django 2.1.5 on 2019-02-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='날')),
                ('start_time', models.TimeField(verbose_name='시작일')),
                ('end_time', models.TimeField(verbose_name='마감일')),
                ('notes', models.CharField(max_length=50, verbose_name='상세')),
            ],
            options={
                'verbose_name': '이벤트 데이터',
                'verbose_name_plural': '이벤트 데이터',
                'ordering': ['start_time'],
            },
        ),
    ]
