# Generated by Django 2.1.5 on 2019-02-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['day'], 'verbose_name': '이벤트 데이터', 'verbose_name_plural': '이벤트 데이터'},
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(verbose_name='마감시간'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.CharField(max_length=50, verbose_name='이벤트 이름'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(verbose_name='시작시간'),
        ),
    ]
