# Generated by Django 2.1.5 on 2019-02-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190227_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': '이벤트 데이터', 'verbose_name_plural': '이벤트 데이터'},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='notes',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='day',
        ),
    ]
