# Generated by Django 2.1.5 on 2019-02-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190227_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='이것은 모델 설명 추가 테스트이다', verbose_name='상세'),
            preserve_default=False,
        ),
    ]
